export const JARV_PRODUCTS = [
  {
    sku: 'JRV-CHS-001',
    product_name: 'Bonded Aluminium Chassis Tub',
    category: 'Chassis',
    price: 640000,
    quantity: 4,
    description: 'Bonded and riveted aluminium spaceframe tub with floor pan, carpets and firewall. The foundation every R-01 is built on.',
    specs: { Material: '6061-T6 aluminium', Torsional: '36,000 Nm/deg', Weight: '118 kg' },
    three_part: 'chassis',
    image: '/parts/product-chassis.jpg',
  },
  {
    sku: 'JRV-WHL-004',
    product_name: 'Forged 20" Wheel & Tire Set ×4',
    category: 'Wheels & Brakes',
    price: 489000,
    quantity: 8,
    description: 'Five-spoke forged monoblock wheels on performance rubber, centre-lock caps and titanium nuts. Balanced and torqued out of the box.',
    specs: { Size: '20×8.5 F / 20×11 R', Tires: '245/35 · 295/35', Nuts: 'Titanium' },
    three_part: 'wheels',
    image: '/parts/product-wheel.jpg',
  },
  {
    sku: 'JRV-BRK-401',
    product_name: 'Carbon-Ceramic Brake Kit',
    category: 'Wheels & Brakes',
    price: 734000,
    quantity: 6,
    description: 'Cross-drilled carbon-ceramic discs with six-piston monobloc calipers. Fades 40% later than iron and lasts the life of the car.',
    specs: { Discs: '398 mm CCM', Caliper: '6-piston monobloc', 'Weight saving': '-18 kg' },
    three_part: 'brakes',
    image: '/parts/product-brake.jpg',
  },
  {
    sku: 'JRV-INT-220',
    product_name: 'Leather Interior & Steering Kit',
    category: 'Interior',
    price: 412000,
    quantity: 7,
    description: 'Hand-stitched leather buckets, dash trim and a carbon steering wheel with integrated shift-light LEDs.',
    specs: { Seats: 'Carbon-shell buckets', Wheel: 'Carbon + LED shift lights', Stitch: 'Contrast red' },
    three_part: 'interior',
    image: '/parts/product-interior.jpg',
  },
  {
    sku: 'JRV-BDY-001',
    product_name: 'Rosso Body Shell + Carbon Kit',
    category: 'Body & Panels',
    price: 985000,
    quantity: 3,
    description: 'Complete aluminium outer skin in Rosso Corsa clearcoat with carbon splitter, side blades and diffuser.',
    specs: { Panels: 'Aluminium + carbon', Finish: 'Rosso Corsa / clearcoat', Weight: '86 kg' },
    three_part: 'body',
    image: '/parts/product-body.jpg',
  },
  {
    sku: 'JRV-GLS-201',
    product_name: 'Panoramic Glass Set + Wipers',
    category: 'Glass & Trim',
    price: 168000,
    quantity: 12,
    description: 'Acoustic laminated windscreen, side and engine-cover glass, plus the aero wiper assembly.',
    specs: { Tint: 'Grey 35% VLT', Laminate: 'Acoustic PVB', Wipers: 'Single-arm aero' },
    three_part: 'glass',
    image: '/parts/product-glass.jpg',
  },
  {
    sku: 'JRV-HLT-310',
    product_name: 'Adaptive LED Headlights (Pair)',
    category: 'Lighting',
    price: 215000,
    quantity: 10,
    description: 'Projector LED units with signature DRL strip and amber sequential indicators. Plug-and-play on the R-01 harness.',
    specs: { Beam: '5500 K projector', DRL: 'LED signature', Output: '6,200 lm / unit' },
    three_part: 'headlights',
    image: '/parts/product-headlights.jpg',
  },
  {
    sku: 'JRV-TLT-318',
    product_name: 'Round LED Taillights (Set)',
    category: 'Lighting',
    price: 92000,
    quantity: 14,
    description: 'Twin-round LED taillight clusters with smoked lenses and sequential brake flash.',
    specs: { Type: 'Twin round', Lens: 'Smoked', Sealed: 'IP67' },
    three_part: 'taillights',
    image: '/parts/product-taillights.jpg',
  },
  {
    sku: 'JRV-GRL-042',
    product_name: 'Honeycomb Grille Set',
    category: 'Body & Panels',
    price: 48000,
    quantity: 22,
    description: 'Front intake, side-pod and rear diffuser honeycomb grilles, laser-cut and powder-coated satin black.',
    specs: { Pieces: '7-piece set', Mesh: 'Honeycomb', Finish: 'Satin black' },
    three_part: 'grilles',
    image: '/parts/product-grilles.jpg',
  },
  {
    sku: 'JRV-CHR-707',
    product_name: 'Chrome Trim & Exhaust Tips',
    category: 'Performance',
    price: 76000,
    quantity: 16,
    description: 'Polished triple exhaust finishers, badges and chrome accents. The last thing to go on — the first thing people see.',
    specs: { Tips: 'Triple 90 mm', Material: 'Polished stainless', Badges: 'Included' },
    three_part: 'chrome',
    image: '/parts/product-chrome.jpg',
  },
  {
    sku: 'JRV-SUS-460',
    product_name: 'Adjustable Coilover Suspension',
    category: 'Chassis',
    price: 98000,
    quantity: 14,
    description: 'Gas-charged coilovers, 30-way compression and rebound. Adjustable from the wheel well, no jacking.',
    specs: { Travel: '110 mm', Adjustment: '30-way c+r', Spring: '3.0 kg/cm' },
    three_part: null,
    image: '/parts/product-coilover.jpg',
  },
  {
    sku: 'JRV-TRB-808',
    product_name: 'VGT Turbocharger Kit',
    category: 'Engine',
    price: 289000,
    quantity: 5,
    description: 'Variable-geometry turbo with billet compressor wheel, custom manifold and heat wrap kit.',
    specs: { Type: 'VGT', Boost: 'Up to 2.1 bar', Compressor: 'Billet, 61 mm' },
    three_part: 'engine',
    image: '/parts/product-turbo.jpg',
  },
  {
    sku: 'JRV-INT-812',
    product_name: 'Cold-Air Intake System',
    category: 'Engine',
    price: 31000,
    quantity: 22,
    description: 'Machined 74 mm inlet and conical filter. Adds 9 hp at the crank on the dyno sheet.',
    specs: { Inlet: '74 mm machined', Filter: 'Conical, reusable', Gain: '+9 hp @ crank' },
    three_part: null,
    image: '/parts/product-intake.jpg',
  },
  {
    sku: 'JRV-DRV-630',
    product_name: 'Limited-Slip Differential',
    category: 'Drivetrain',
    price: 172000,
    quantity: 7,
    description: '1.5-way LSD with 35% bias, bronze gears, and a reinforced carrier.',
    specs: { Bias: '35% / 1.5-way', Gears: 'Bronze', Carrier: 'Forged' },
    three_part: null,
    image: '/parts/product-differential.jpg',
  },
  {
    sku: 'JRV-ELC-915',
    product_name: '12V Lithium Power Pack',
    category: 'Electrical',
    price: 46000,
    quantity: 19,
    description: 'Sealed LiFePO4 pack. 4× the cold-cranking amps, 60% lighter, 10-year life.',
    specs: { Chemistry: 'LiFePO4', CCA: '1,100 A', Weight: '2.1 kg' },
    three_part: null,
    image: '/parts/product-battery.jpg',
  },
];
